config:
  info: "Master branch, SpringCloud-Config/config-dev.yml version=1"
  
spring:
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&useOldAliasMetadataBehavior=true
    username: root
    password: 123
